<?php

return [
    'organization' => [
        'name' => 'Nuts Paradise',
        'description' => 'South African processor and exporter of macadamia and cashew products for professional international buyers.',
        'email' => 'info@nutsparadise.co.za',
        'telephone' => '+27 76 020 4666',
        'logo' => '/logo.webp',
        'locations' => [
            [
                'name' => 'Nuts Paradise Processing Facility',
                'street_address' => 'Riverside Park Industrial Zone, Rapid Street, Riverside Park',
                'locality' => 'Mbombela',
                'country' => 'ZA',
            ],
            [
                'name' => 'Nuts Paradise Administrative Office',
                'street_address' => '222 Smit Street, Braamfontein',
                'locality' => 'Johannesburg',
                'postal_code' => '2000',
                'country' => 'ZA',
            ],
        ],
        'knows_about' => [
            'Macadamia processing',
            'Cashew processing',
            'FSSC 22000 certified nut processing',
            'Nut quality management',
            'Export preparation for professional buyers',
        ],
    ],

    'pages' => [
        'home' => [
            'label' => 'Home',
            'type' => 'WebPage',
            'indexable' => true,
            'lastmod' => '2026-09-09',
            'title' => 'South African Macadamia & Cashew Processor | Nuts Paradise',
            'description' => 'Nuts Paradise processes and exports macadamia and cashew products from South Africa, with FSSC 22000 certified processing in Mbombela and capacity of up to 1,000 MT per month.',
        ],
        'about' => [
            'label' => 'About Us',
            'type' => 'AboutPage',
            'indexable' => true,
            'lastmod' => '2026-09-09',
            'title' => 'South African Nut Processor & Exporter | Nuts Paradise',
            'description' => 'Learn about Nuts Paradise, a South African macadamia and cashew processor and exporter with processing in Mbombela and administration in Johannesburg.',
        ],
        'products.index' => [
            'label' => 'Products',
            'type' => 'CollectionPage',
            'indexable' => true,
            'lastmod' => '2026-09-09',
            'title' => 'Macadamia & Cashew Supply for B2B Buyers | Nuts Paradise',
            'description' => 'Explore South African-processed macadamia and cashew products for importers, distributors, food manufacturers, retailers and ingredient buyers.',
        ],
        'products.macadamias' => [
            'label' => 'Macadamias',
            'type' => 'WebPage',
            'indexable' => true,
            'parent' => 'products.index',
            'lastmod' => '2026-09-09',
            'title' => 'South African Macadamia Processor | Nuts Paradise',
            'description' => 'Discuss South African-processed macadamia supply with Nuts Paradise for international food, ingredient, distribution and retail requirements.',
        ],
        'products.cashews' => [
            'label' => 'Cashews',
            'type' => 'WebPage',
            'indexable' => true,
            'parent' => 'products.index',
            'lastmod' => '2026-09-09',
            'title' => 'South African Cashew Processor & Exporter | Nuts Paradise',
            'description' => 'Discuss cashew processing and professional export supply with Nuts Paradise for food, ingredient, distribution and retail buyers.',
        ],
        'processing' => [
            'label' => 'Processing',
            'type' => 'WebPage',
            'indexable' => true,
            'lastmod' => '2026-09-09',
            'title' => 'Macadamia & Cashew Processing in Mbombela | Nuts Paradise',
            'description' => 'Nuts Paradise processes macadamias and cashews at Riverside Park in Mbombela, South Africa, with capacity of up to 1,000 MT per month.',
        ],
        'quality' => [
            'label' => 'Quality & Certification',
            'type' => 'WebPage',
            'indexable' => true,
            'lastmod' => '2026-09-09',
            'title' => 'FSSC 22000 Certified Nut Processing | Nuts Paradise',
            'description' => 'Nuts Paradise provides FSSC 22000 certified processing for both macadamias and cashews in South Africa, supported by quality management and buyer-focused documentation.',
        ],
        'traceability' => [
            'label' => 'Traceability',
            'type' => 'WebPage',
            'indexable' => true,
            'lastmod' => '2026-09-09',
            'title' => 'Nut Processing Traceability & Documentation | Nuts Paradise',
            'description' => 'Learn how Nuts Paradise supports product identification, processing records, quality documentation and export preparation for professional macadamia and cashew supply.',
        ],
        'buyers' => [
            'label' => 'Buyers',
            'type' => 'WebPage',
            'indexable' => true,
            'lastmod' => '2026-09-09',
            'title' => 'Macadamia & Cashew Supply for International Buyers | Nuts Paradise',
            'description' => 'Nuts Paradise works with importers, distributors, food manufacturers, retail teams and ingredient buyers seeking South African-processed macadamia and cashew supply.',
        ],
        'export-markets' => [
            'label' => 'Export Markets',
            'type' => 'WebPage',
            'indexable' => true,
            'lastmod' => '2026-09-09',
            'title' => 'Macadamia & Cashew Export Supply from South Africa | Nuts Paradise',
            'description' => 'Nuts Paradise prepares South African-processed macadamias and cashews around international buyer requirements, quality documentation and export preparation.',
        ],
        'contact' => [
            'label' => 'Contact Us',
            'type' => 'ContactPage',
            'indexable' => true,
            'lastmod' => '2026-09-09',
            'title' => 'Contact a South African Nut Processor | Nuts Paradise',
            'description' => 'Contact Nuts Paradise about macadamia and cashew processing, product requirements, estimated volumes, destination markets and professional supply enquiries.',
        ],
        'privacy' => [
            'label' => 'Privacy Policy',
            'type' => 'WebPage',
            'indexable' => false,
            'lastmod' => '2026-09-09',
        ],
        'terms' => [
            'label' => 'Terms of Use',
            'type' => 'WebPage',
            'indexable' => false,
            'lastmod' => '2026-09-09',
        ],
    ],
];
